### ISSUE TITLE
Which version of PECL gearman and gearman server is usable with behat?

### ISSUE THREAD

**Issue by neochief** [vipsoft/BehatGearmanExtension#1]
Hi!

Can you advise, which version of PECL gearman library and which version of gearman suppose to work with your extension? I tried multiple variations, but it looks like the php library outdated and don't work with latest gearman server.

Just for the record, when I try to run a client or worker I get a lot of this:
Warning: GearmanClient::addTask(): add_task(GEARMAN_INVALID_ARGUMENT) invalid function -> libgearman/add.cc:183

**Comment by nickschuch** [comment]
I to have tried this and cannot work out how to get it running.

**Comment by neochief** [comment]
I remember I had to change 'localhost' to '127.0.0.1' somewhere in gearman server connection calls to make it work.

**Comment by robocoder** [comment]
Sorry for the delay in responding.

This extension was developed on Ubuntu 12.04 LTS -- the package repo provides libgearman 0.27.  I used the gearman 1.0.2 extension from pecl.

If you use the latest version of the gearman extension from pecl (i.e., 1.1.0 or above), then you'll need to upgrade libgearman to 1.1.\* (e.g., 1.1.8).
