### ISSUE TITLE
Documentation disappeared

### ISSUE THREAD

**Issue by black-goldfinch** [vipsoft/BehatGearmanExtension#5]
Hi Anthon.

I'm trying to make our behat run in parallel and the first problem I face is broken link to documentation.
Could you please publish or send me a  copy so I can publish it?
Thank you

**Comment by robocoder** [comment]
Thanks for the heads up.  I'll update links to point to the github hosted docs.

e.g., https://github.com/vipsoft/BehatGearmanExtension/blob/master/doc/index.rst

**Comment by black-goldfinch** [comment]
Thank you very much!
